# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

services:
  rabbitfoodapi:
    image: rabbitfoodapi
    build:
      args:
        - configuration=Debug
    ports:
      - 5077:5077
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
  rabbitfoodconsumer:
    image: rabbitfoodconsumer
    build:
      args:
        - configuration=Debug
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
